AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  algoa-gtfs

  Sample SAM Template for algoa-gtfs
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  AlgoaGtfsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: generate-gtfs/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        GenerateGtfs:
          Type: Schedule
          Properties:
            Schedule: rate(1 days)
            Name: daily
            Enabled: False
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts

Outputs:
  AlgoaGtfsFunctionArn:
    Description: "Lambda Function ARN"
    Value: !GetAtt AlgoaGtfsFunction.Arn
  AlgoaGtfsFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt AlgoaGtfsFunctionRole.Arn
